---
_format_version: "1.1"
services:
  - name: authenticid
    url: https://cfwebt.amalgam-east.ascendant.cloud
    routes:
      - name: authenticid-route
        paths:
          - /wombat
        protocols:
          - http
  - name: socure
    url: https://verify-v2.general.socure.com/
    routes:
      - name: socure-route
        paths:
          - /badger
        protocols:
          - http
plugins:
  - name: prometheus
