---
_format_version: "1.1"
services:
  - name: authenticid
    url: https://cfwebt.amalgam-east.ascendant.cloud
    routes:
      - name: authenticid-route
        paths:
          - /authenticid
        protocols:
          - http
plugins:
  - name: prometheus
