---
_format_version: "1.1"
services:
  - name: sk-api
    url: https://identity-idva-sk-api-${ENVIRONMENT_NAME}.apps.internal:61443
    routes:
      - name: sk-api-route
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        hosts:
          - idva-api-${ENVIRONMENT_NAME}.app.cloud.gov
        protocols:
          - http
  - name: keycloak
    url: https://identity-idva-keycloak-${ENVIRONMENT_NAME}.apps.internal:61443
    routes:
      - name: keycloak-route
        paths:
          - /realms/
          - /resources/
          - /robots.txt
        strip_path: false
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        hosts:
          - idva-keycloak-${ENVIRONMENT_NAME}.app.cloud.gov
        protocols:
          - http
plugins:
  - name: prometheus
  - name: response-transformer
    route: keycloak-route
    config: 
      add:
        headers:
        - X-Frame-Options:ALLOWALL
