---
_format_version: "1.1"
services:
  - name: sk-api
    url: http://identity-idva-sk-api-${ENVIRONMENT_NAME}.apps.internal:8080
    routes:
      - name: sk-api-route
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        hosts:
          - idva-api-${ENVIRONMENT_NAME}.app.cloud.gov
        protocols:
          - http
plugins:
  - name: prometheus
