---
_format_version: "1.1"
services:
  - name: sk-api
    url: https://identity-idva-sk-api-${ENVIRONMENT_NAME}.apps.internal:61443
    routes:
      - name: sk-api-route
        hosts:
          - idva-api-${ENVIRONMENT_NAME}.app.cloud.gov
        protocols:
          - http
  - name: sk-portal
    url: https://idva-sk-portal-${ENVIRONMENT_NAME}.apps.internal:61443
    routes:
      - name: sk-portal-route
        hosts:
          - idva-portal-${ENVIRONMENT_NAME}.app.cloud.gov
        protocols:
          - http
  - name: sk-sdk
    url: https://idva-sk-sdk-${ENVIRONMENT_NAME}.apps.internal:61443
    routes:
      - name: sk-sdk-route
        hosts:
          - idva-sdk-${ENVIRONMENT_NAME}.app.cloud.gov
        protocols:
          - http
  - name: authenticid
    url: https://idva-kong-egress-${ENVIRONMENT_NAME}.apps.internal:61443
    routes:
      - name: authenticid-route
        paths:
          - /wombat
        strip_path: false
        hosts:
          - idva-${ENVIRONMENT_NAME}.app.cloud.gov
        protocols:
          - http
  - name: incode
    url: https://idva-incode-${ENVIRONMENT_NAME}.apps.internal:61443
    routes:
      - name: incode-route
        hosts:
          - idva-marmot-${ENVIRONMENT_NAME}.app.cloud.gov
        protocols:
          - http
plugins:
  - name: prometheus
