---
_format_version: "1.1"
services:

  - name: grafana
    url: https://identity-idva-monitoring-grafana-${ENVIRONMENT_NAME}.apps.internal:61443/
    routes:
      - name: grafana-host-route
        hosts:
          - identity-idva-monitoring-grafana-${ENVIRONMENT_NAME}.apps.internal
        protocols:
          - http

      - name: grafana-path-route
        paths:
          - /grafana
        protocols:
          - http
        strip_path: false

  - name: prometheus
    url: https://identity-idva-monitoring-prometheus-${ENVIRONMENT_NAME}.apps.internal:61443/
    routes:
      - name: prometheus-host-route
        hosts:
          - identity-idva-monitoring-prometheus-${ENVIRONMENT_NAME}.apps.internal
        protocols:
          - http

      - name: prometheus-path-route
        paths:
          - /prometheus
        protocols:
          - http
        strip_path: false

  - name: alertmanager
    url: https://identity-idva-monitoring-alertmanager-${ENVIRONMENT_NAME}.apps.internal:61443/
    routes:
      - name: alertmanager-host-route
        hosts:
          - identity-idva-monitoring-alertmanager-${ENVIRONMENT_NAME}.apps.internal
        protocols:
          - http

      - name: alertmanager-path-route
        paths:
          - /alertmanager
        protocols:
          - http
        strip_path: false

  - name: esdashboard
    url: https://identity-idva-es-proxy-${ENVIRONMENT_NAME}.apps.internal:61443/
    routes:
      - name: esdashboard-host-route
        hosts:
          - identity-idva-monitoring-es-proxy-${ENVIRONMENT_NAME}.apps.internal
        protocols:
          - http

      - name: esdashboard-path-route
        paths:
          - /_dashboards
        protocols:
          - http
        strip_path: false

plugins:
  - name: prometheus
