---
# This workflow will validate the Kong decK state file and deploy
# the application to a target environment

name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - '**.md'  # All markdown files in the repository
  release:
    types: [released]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install decK CLI
        run: |
          brew tap kong/deck
          brew install deck
          deck version

      - name: Validate the Kong config file
        run: |
          export ENVIRONMENT_NAME=dev
          envsubst < kong-config.yaml > kong.yaml
          deck validate --state kong.yaml

      - name: Install Kong
        run: |
          echo "deb [trusted=yes] https://download.konghq.com/gateway-2.x-ubuntu-$(lsb_release -sc)/ default all" | sudo tee /etc/apt/sources.list.d/kong.list 
          sudo apt-get update
          sudo apt install -y kong

      - name: Validate kong.conf file
        run: kong check ./kong.conf

  deploy:
    if: github.repository_owner == '18F'
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: 18F/identity-give-cf-setup@v1
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Deploy application
        run: cf push --vars-file vars.yaml --var ENVIRONMENT_NAME=${{ steps.deployment-target.outputs.ENVIRONMENT_NAME }}

      - name: Apply CF Network Policies
        run: |
          cf add-network-policy api-gateway sk-api
          cf add-network-policy api-gateway sk-portal
          cf add-network-policy api-gateway sk-sdk
