---
# This workflow will run the OWASP ZAP web application security scanner against
# the IDVA API Gateway

name: Zap-Scan-Portal

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - '**.md'  # All markdown files in the repository

jobs:
  zap_scan_api:
    runs-on: ubuntu-latest
    name: Scan the API Gateway - Portal
    steps:
      - uses: actions/checkout@v2

      - name: ZAP Scan (Portal)
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: "https://idva-portal-dev.app.cloud.gov"
          rules_file_name: ".zap/rules-portal.tsv"
          issue_title: "ZAP Full Scan Report - Portal"
